# Generated by Django 3.1 on 2020-08-11 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domiciliario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordenada_x', models.IntegerField()),
                ('coordenada_y', models.IntegerField()),
            ],
        ),
    ]
