# Generated by Django 3.1 on 2020-08-12 22:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domiciliario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_domiciliario', models.IntegerField()),
                ('y_domiciliario', models.IntegerField()),
                ('x_pedido', models.IntegerField()),
                ('y_pedido', models.IntegerField()),
                ('id_domiciliario_escogido', models.IntegerField()),
                ('distancia', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=8)),
            ],
        ),
    ]
